#!/usr/bin/env bash


USAGE="Usage: $(basename $0) [--help] [-v|--verbose] DIR"

if [[ -z "$1" ]] || [[ ! -d "$1" ]]; then
    echo "$USAGE"
    exit 1
fi

declare -A photolist

printf "PHOTOID_SHA256 PHOTOID_INFO FILENAME\n"
find "$1" -type f ! -path "*/@eaDir/*" | while read; do

    FILE="$REPLY"

    if [[ ! -f "$FILE" ]]; then
        echo "Error. Not a file: '$FILE'" >&2
        shift
        continue
    fi

    mime="$(file -b --mime-type "$FILE")"

    case "$mime" in
        image/tiff) 
            supported=1
            ;;
        image/jpeg)
            supported=1
            ;;
        *)
            supported=0
            echo "Error. File '$FILE' is an usupported type: $mime." >&2
            shift
            continue
            ;;
    esac


    normalized_filename=$(echo $(basename "$FILE") | sed -e 's/\.NEF//' -e 's/\.JPG//' -e  's/\.nef//' -e 's/\.jpg//' | sed -e 's/\(^[^\s]\+\)\s.*/\1/' )
    photoid_exif="$(exiftool -f -api MissingTagValue='undef' -d '%Y%m%d_%H%M%S' -n -p '$ShutterCount $DateTimeOriginal $SubSecTime $ExposureTime $FNumber $ISO $FocalLengthIn35mmFormat $FOV $FocusDistance $LightValue $GainControl $Make $Model' "$FILE" 2>/dev/null | tr ' ' '_' )"
    photoid="${photoid_exif}"
    photoid_sha256="$(echo ${photoid_exif} | sha256sum | cut -d ' ' -f 1)"

    #echo "photoid=$photoid"
    if [[ -n "$photoid" ]]; then
        printf '%s %s "%s"\n' $photoid_sha256 $photoid "$FILE" 
    fi
    shift
done
