#!/usr/bin/env bash

shrtrhome=~/.s
template="XXXX"

name="$(basename "$1")"
fn="$(readlink -f "$1")"

function out(){
nn=$(echo $1| sed "s#$HOME#~#")
echo "$name - $nn"
if [ -x /usr/bin/xclip ]; then
    echo "$name - $nn" | xclip
fi
}

if [ ! -f "$fn" ] || [ -z "$fn" ] ; then 
    echo "No such file: '$fn'" >&2
    exit -1 
fi

[ ! -d "${shrtrhome}" ] && mkdir "${shrtrhome}"

#find_unique_name 
for l in $shrtrhome/*; do
    ln="$(readlink -f "$l")"
    if [ "$ln" == "$fn" ]; then
        out $l
        exit 0
    fi
done

shrtname="$(mktemp -u --tmpdir=$shrtrhome $template)"

ln -sf $fn $shrtname

out $shrtname
exit 0

